from random import randint

# The intent of this module is to provide a simple tool that can
# randomly choose a city to be supplied to the weather forecast agent,
# should the user provide no input.
# Out of all possibilities which would make this module far more complex
# than the rest of the application, and would likely make the end app
# less portable, I believe that embedding a number of city names (100)
# into the application code is the simplest and cleanest solution.
CITIES = [
    "Athens",
    "Thessaloniki",
    "Kavala",
    "Vilnius",
    "Kaunas",
    "Klaipeda",
    "Alytus",
    "Riga",
    "Liepaja",
    "Venspils",
    "Talin",
    "Helsinki",
    "Oslo",
    "Bergen",
    "Copenhagen",
    "Aarhus",
    "Stockholm",
    "Gothenburg",
    "Upsala",
    "Malmo",
    "Berlin",
    "Frankfurt",
    "Koln",
    "Warsaw",
    "Krakow",
    "Katowice",
    "Paris",
    "Lyon",
    "Nice",
    "Marseilles",
    "Amsterdam",
    "Rotterdam",
    "Waggenigen",
    "Gdansk",
    "Wroclaw",
    "Munich",
    "Hamburg",
    "Cologne",
    "Dresden",
    "London",
    "Leicester",
    "Manchester",
    "Liverpool",
    "York",
    "Nottingham",
    "Birmingham",
    "Bristol",
    "Utrecht",
    "Breda",
    "Maastricht",
    "The Hague",
    "Bruges",
    "Ghent",
    "Brussels",
    "Antwerp",
    "Mechelen",
    "Bordeaux",
    "Toulouse",
    "Barcelona",
    "Madrid",
    "Seville",
    "Zaragoza",
    "Valencia",
    "Alicante",
    "Porto",
    "Lisbon",
    "Faro",
    "Coimbra",
    "Rome",
    "Florence",
    "Venice",
    "Milan",
    "Naples",
    "Bologna",
    "Turin",
    "Palermo",
    "Bratislava",
    "Poprad",
    "Levoca",
    "Kosice",
    "Ljubljana",
    "Bled",
    "Piran",
    "Zagreb",
    "Split",
    "Dubrovnik",
    "Kotor",
    "Podgorica",
    "Budva",
    "Sarajevo",
    "Viena",
    "Salzburg",
    "Prague",
    "Brno",
    "Pilsen",
    "Bucharest",
    "Cluj-Napoca",
    "Valletta",
    "Marsaxlokk",
]


def pick_random_city() -> str:
    """Provides a random city to be used for weather forecasting, if one is not provided by the user."""
    return CITIES[randint(0, 99)]
